use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct VoicePreset {
    pub id: &'static str,
    pub display_name: &'static str,
    pub locale: &'static str,
    pub gender: &'static str,
    pub category: &'static str,
    pub notes: &'static str,
}

pub const TTS_VOICE_PRESETS: &[VoicePreset] = &[
    VoicePreset {
        id: "zh_female_gaolengyujie_uranus_bigtts",
        display_name: "高冷御姐 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "cool, mature female voice; official Agent Plan examples use this speaker",
    },
    VoicePreset {
        id: "zh_male_aojiaobazong_uranus_bigtts",
        display_name: "傲娇霸总 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "confident CEO-style male voice",
    },
    VoicePreset {
        id: "zh_male_lanyinmianbao_uranus_bigtts",
        display_name: "懒音绵宝 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "role_play",
        notes: "lazy, soft role-play voice",
    },
    VoicePreset {
        id: "zh_male_fanjuanqingnian_uranus_bigtts",
        display_name: "反卷青年 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "casual young male voice",
    },
    VoicePreset {
        id: "zh_female_wenroushunv_uranus_bigtts",
        display_name: "温柔淑女 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "gentle female voice",
    },
    VoicePreset {
        id: "zh_female_gufengshaoyu_uranus_bigtts",
        display_name: "古风少御 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "role_play",
        notes: "ancient-style young female role voice",
    },
    VoicePreset {
        id: "zh_male_huolixiaoge_uranus_bigtts",
        display_name: "活力小哥 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "energetic young male voice",
    },
    VoicePreset {
        id: "zh_male_baqiqingshu_uranus_bigtts",
        display_name: "霸气青叔 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "audiobook",
        notes: "forceful middle-aged male voice, useful for narration",
    },
    VoicePreset {
        id: "zh_male_xuanyijieshuo_uranus_bigtts",
        display_name: "悬疑解说 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "audiobook",
        notes: "mystery narrator voice",
    },
    VoicePreset {
        id: "zh_male_wennuanahu_uranus_bigtts",
        display_name: "温暖阿虎 / Alvin 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "warm male voice; 2.0 uranus variant",
    },
    VoicePreset {
        id: "zh_male_naiqimengwa_uranus_bigtts",
        display_name: "奶气萌娃 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "cute child-like voice",
    },
    VoicePreset {
        id: "zh_female_popo_uranus_bigtts",
        display_name: "婆婆 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "elderly female voice",
    },
    VoicePreset {
        id: "zh_female_mengyatou_uranus_bigtts",
        display_name: "萌丫头 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "cute young female voice",
    },
    VoicePreset {
        id: "zh_female_tiexinnvsheng_uranus_bigtts",
        display_name: "贴心女生 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "friendly, caring female voice",
    },
    VoicePreset {
        id: "zh_female_jitangmei_uranus_bigtts",
        display_name: "鸡汤妹 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "encouraging female voice",
    },
    VoicePreset {
        id: "zh_male_cixingjieshuonan_uranus_bigtts",
        display_name: "磁性解说男 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "magnetic male narrator",
    },
    VoicePreset {
        id: "zh_female_kailangjiejie_uranus_bigtts",
        display_name: "开朗姐姐 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "cheerful female voice",
    },
    VoicePreset {
        id: "zh_male_gaolengchenwen_uranus_bigtts",
        display_name: "高冷沉稳 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "cool and steady male voice",
    },
    VoicePreset {
        id: "zh_male_shenyeboke_uranus_bigtts",
        display_name: "深夜播客 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "late-night podcast style",
    },
    VoicePreset {
        id: "zh_female_qinqienv_uranus_bigtts",
        display_name: "亲切女声 2.0",
        locale: "zh-CN",
        gender: "female",
        category: "general",
        notes: "kind and approachable female voice",
    },
    VoicePreset {
        id: "zh_male_kailangxuezhang_uranus_bigtts",
        display_name: "开朗学长 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "cheerful senior male voice",
    },
    VoicePreset {
        id: "zh_male_youyoujunzi_uranus_bigtts",
        display_name: "悠悠君子 2.0",
        locale: "zh-CN",
        gender: "male",
        category: "general",
        notes: "easygoing gentleman voice",
    },
];

pub fn tts_voice_presets() -> &'static [VoicePreset] {
    TTS_VOICE_PRESETS
}
